"""English short names for ISO 3166-1 alpha-3 country codes.

Generated once from the Unicode CLDR territory list (via babel 2.18) with a few
shorter common names; static so the interfaces have no runtime dependency.
Unknown codes are shown as the code itself.
"""

from __future__ import annotations

COUNTRY_NAMES: dict[str, str] = {
    "ABW": 'Aruba',
    "AFG": 'Afghanistan',
    "AGO": 'Angola',
    "AIA": 'Anguilla',
    "ALA": 'Åland Islands',
    "ALB": 'Albania',
    "AND": 'Andorra',
    "ARE": 'United Arab Emirates',
    "ARG": 'Argentina',
    "ARM": 'Armenia',
    "ASC": 'Ascension Island',
    "ASM": 'American Samoa',
    "ATA": 'Antarctica',
    "ATF": 'French Southern Territories',
    "ATG": 'Antigua & Barbuda',
    "AUS": 'Australia',
    "AUT": 'Austria',
    "AZE": 'Azerbaijan',
    "BDI": 'Burundi',
    "BEL": 'Belgium',
    "BEN": 'Benin',
    "BES": 'Caribbean Netherlands',
    "BFA": 'Burkina Faso',
    "BGD": 'Bangladesh',
    "BGR": 'Bulgaria',
    "BHR": 'Bahrain',
    "BHS": 'Bahamas',
    "BIH": 'Bosnia & Herzegovina',
    "BLM": 'St. Barthélemy',
    "BLR": 'Belarus',
    "BLZ": 'Belize',
    "BMU": 'Bermuda',
    "BOL": 'Bolivia',
    "BRA": 'Brazil',
    "BRB": 'Barbados',
    "BRN": 'Brunei',
    "BTN": 'Bhutan',
    "BUR": 'Myanmar (Burma)',
    "BVT": 'Bouvet Island',
    "BWA": 'Botswana',
    "CAF": 'Central African Republic',
    "CAN": 'Canada',
    "CCK": 'Cocos (Keeling) Islands',
    "CHE": 'Switzerland',
    "CHL": 'Chile',
    "CHN": 'China',
    "CIV": 'Côte d’Ivoire',
    "CMR": 'Cameroon',
    "COD": 'DR Congo',
    "COG": 'Congo',
    "COK": 'Cook Islands',
    "COL": 'Colombia',
    "COM": 'Comoros',
    "CPT": 'Clipperton Island',
    "CPV": 'Cape Verde',
    "CRI": 'Costa Rica',
    "CUB": 'Cuba',
    "CUW": 'Curaçao',
    "CXR": 'Christmas Island',
    "CYM": 'Cayman Islands',
    "CYP": 'Cyprus',
    "CZE": 'Czechia',
    "DDR": 'Germany',
    "DEU": 'Germany',
    "DGA": 'Diego Garcia',
    "DJI": 'Djibouti',
    "DMA": 'Dominica',
    "DNK": 'Denmark',
    "DOM": 'Dominican Republic',
    "DZA": 'Algeria',
    "ECU": 'Ecuador',
    "EGY": 'Egypt',
    "ERI": 'Eritrea',
    "ESH": 'Western Sahara',
    "ESP": 'Spain',
    "EST": 'Estonia',
    "ETH": 'Ethiopia',
    "FIN": 'Finland',
    "FJI": 'Fiji',
    "FLK": 'Falkland Islands',
    "FRA": 'France',
    "FRO": 'Faroe Islands',
    "FSM": 'Micronesia',
    "FXX": 'France',
    "GAB": 'Gabon',
    "GBR": 'United Kingdom',
    "GEO": 'Georgia',
    "GGY": 'Guernsey',
    "GHA": 'Ghana',
    "GIB": 'Gibraltar',
    "GIN": 'Guinea',
    "GLP": 'Guadeloupe',
    "GMB": 'Gambia',
    "GNB": 'Guinea-Bissau',
    "GNQ": 'Equatorial Guinea',
    "GRC": 'Greece',
    "GRD": 'Grenada',
    "GRL": 'Greenland',
    "GTM": 'Guatemala',
    "GUF": 'French Guiana',
    "GUM": 'Guam',
    "GUY": 'Guyana',
    "HKG": 'Hong Kong',
    "HMD": 'Heard & McDonald Islands',
    "HND": 'Honduras',
    "HRV": 'Croatia',
    "HTI": 'Haiti',
    "HUN": 'Hungary',
    "IDN": 'Indonesia',
    "IMN": 'Isle of Man',
    "IND": 'India',
    "IOT": 'British Indian Ocean Territory',
    "IRL": 'Ireland',
    "IRN": 'Iran',
    "IRQ": 'Iraq',
    "ISL": 'Iceland',
    "ISR": 'Israel',
    "ITA": 'Italy',
    "JAM": 'Jamaica',
    "JEY": 'Jersey',
    "JOR": 'Jordan',
    "JPN": 'Japan',
    "KAZ": 'Kazakhstan',
    "KEN": 'Kenya',
    "KGZ": 'Kyrgyzstan',
    "KHM": 'Cambodia',
    "KIR": 'Kiribati',
    "KNA": 'St. Kitts & Nevis',
    "KOR": 'South Korea',
    "KWT": 'Kuwait',
    "LAO": 'Laos',
    "LBN": 'Lebanon',
    "LBR": 'Liberia',
    "LBY": 'Libya',
    "LCA": 'St. Lucia',
    "LIE": 'Liechtenstein',
    "LKA": 'Sri Lanka',
    "LSO": 'Lesotho',
    "LTU": 'Lithuania',
    "LUX": 'Luxembourg',
    "LVA": 'Latvia',
    "MAC": 'Macao',
    "MAF": 'St. Martin',
    "MAR": 'Morocco',
    "MCO": 'Monaco',
    "MDA": 'Moldova',
    "MDG": 'Madagascar',
    "MDV": 'Maldives',
    "MEX": 'Mexico',
    "MHL": 'Marshall Islands',
    "MKD": 'North Macedonia',
    "MLI": 'Mali',
    "MLT": 'Malta',
    "MMR": 'Myanmar',
    "MNE": 'Montenegro',
    "MNG": 'Mongolia',
    "MNP": 'Northern Mariana Islands',
    "MOZ": 'Mozambique',
    "MRT": 'Mauritania',
    "MSR": 'Montserrat',
    "MTQ": 'Martinique',
    "MUS": 'Mauritius',
    "MWI": 'Malawi',
    "MYS": 'Malaysia',
    "MYT": 'Mayotte',
    "NAM": 'Namibia',
    "NCL": 'New Caledonia',
    "NER": 'Niger',
    "NFK": 'Norfolk Island',
    "NGA": 'Nigeria',
    "NIC": 'Nicaragua',
    "NIU": 'Niue',
    "NLD": 'Netherlands',
    "NOR": 'Norway',
    "NPL": 'Nepal',
    "NRU": 'Nauru',
    "NZL": 'New Zealand',
    "OMN": 'Oman',
    "PAK": 'Pakistan',
    "PAN": 'Panama',
    "PCN": 'Pitcairn Islands',
    "PER": 'Peru',
    "PHL": 'Philippines',
    "PLW": 'Palau',
    "PNG": 'Papua New Guinea',
    "POL": 'Poland',
    "PRI": 'Puerto Rico',
    "PRK": 'North Korea',
    "PRT": 'Portugal',
    "PRY": 'Paraguay',
    "PSE": 'Palestine',
    "PYF": 'French Polynesia',
    "QAT": 'Qatar',
    "QUU": 'European Union',
    "REU": 'Réunion',
    "ROU": 'Romania',
    "RUS": 'Russia',
    "RWA": 'Rwanda',
    "SAU": 'Saudi Arabia',
    "SDN": 'Sudan',
    "SEN": 'Senegal',
    "SGP": 'Singapore',
    "SGS": 'South Georgia & South Sandwich Islands',
    "SHN": 'St. Helena',
    "SJM": 'Svalbard & Jan Mayen',
    "SLB": 'Solomon Islands',
    "SLE": 'Sierra Leone',
    "SLV": 'El Salvador',
    "SMR": 'San Marino',
    "SOM": 'Somalia',
    "SPM": 'St. Pierre & Miquelon',
    "SRB": 'Serbia',
    "SSD": 'South Sudan',
    "STP": 'São Tomé & Príncipe',
    "SUR": 'Suriname',
    "SVK": 'Slovakia',
    "SVN": 'Slovenia',
    "SWE": 'Sweden',
    "SWZ": 'Eswatini',
    "SXM": 'Sint Maarten',
    "SYC": 'Seychelles',
    "SYR": 'Syria',
    "TAA": 'Tristan da Cunha',
    "TCA": 'Turks & Caicos Islands',
    "TCD": 'Chad',
    "TGO": 'Togo',
    "THA": 'Thailand',
    "TJK": 'Tajikistan',
    "TKL": 'Tokelau',
    "TKM": 'Turkmenistan',
    "TLS": 'Timor-Leste',
    "TMP": 'Timor-Leste',
    "TON": 'Tonga',
    "TTO": 'Trinidad & Tobago',
    "TUN": 'Tunisia',
    "TUR": 'Türkiye',
    "TUV": 'Tuvalu',
    "TWN": 'Taiwan',
    "TZA": 'Tanzania',
    "UGA": 'Uganda',
    "UKR": 'Ukraine',
    "UMI": 'U.S. Outlying Islands',
    "URY": 'Uruguay',
    "USA": 'United States',
    "UZB": 'Uzbekistan',
    "VAT": 'Vatican City',
    "VCT": 'St. Vincent & Grenadines',
    "VEN": 'Venezuela',
    "VGB": 'British Virgin Islands',
    "VIR": 'U.S. Virgin Islands',
    "VNM": 'Vietnam',
    "VUT": 'Vanuatu',
    "WLF": 'Wallis & Futuna',
    "WSM": 'Samoa',
    "XAA": 'Pseudo-Accents',
    "XBB": 'Pseudo-Bidi',
    "XKK": 'Kosovo',
    "XKX": 'Kosovo',
    "YEM": 'Yemen',
    "YMD": 'Yemen',
    "ZAF": 'South Africa',
    "ZAR": 'Congo - Kinshasa',
    "ZMB": 'Zambia',
    "ZWE": 'Zimbabwe',
    "ZZZ": 'Unknown Region',
}


def country_name(code: str | None) -> str:
    """Readable name for an ISO3 code (the code itself when unknown)."""

    if not code:
        return "Unknown country"
    return COUNTRY_NAMES.get(str(code).upper(), str(code))


def country_label(code: str | None) -> str:
    """Name with the code, for selectors: 'Philippines (PHL)'."""

    return f"{country_name(code)} ({code})" if code and str(code).upper() in COUNTRY_NAMES else str(code or "Unknown country")
